[package]
name = "AES-encryptor"
version = "1.0.0"
edition = "2021"
authors = ["Rik de Goede"]
description = "Minimalistic terminal application to encrypt/decrypt files using AES-GCM (256 bits)."

[dependencies]
aes-gcm = "0.10"
sha2 = "0.10"
rand = "0.8"
pbkdf2 = "0.12"
